services:
  localstack:
    image: localstack/localstack:3
    container_name: flash-sale-localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=sqs,dynamodb
      - DEFAULT_REGION=us-east-1
      - PERSISTENCE=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    image: postgres:16-alpine
    container_name: flash-sale-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: flashsale
      POSTGRES_PASSWORD: flashsale
      POSTGRES_DB: flashsale
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
