from enum import StrEnum


# Constants for the Saga pattern implementation
class EventType(StrEnum):
    PROCESS_PAYMENT = "ProcessPayment"
    PAYMENT_SUCCESS = "PaymentSuccess"
    INVENTORY_FAILED = "InventoryFailed"
    SAGA_COMPLETED = "SagaCompleted"


class SagaOutcome(StrEnum):
    SUCCESS = "SUCCESS"
    ROLLED_BACK = "ROLLED_BACK"
    FAILED_PERMANENTLY = "FAILED_PERMANENTLY"


class PaymentOperation(StrEnum):
    CHARGE = "CHARGE"
    REFUND = "REFUND"


class PaymentStatus(StrEnum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    PENDING = "PENDING"


class IdempotencyStatus(StrEnum):
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ReservationStatus(StrEnum):
    RESERVED = "RESERVED"
    CONFIRMED = "CONFIRMED"
    CANCELLED = "CANCELLED"


class SaleStatus(StrEnum):
    UPCOMING = "UPCOMING"
    ACTIVE = "ACTIVE"
    SOLD_OUT = "SOLD_OUT"
    CLOSED = "CLOSED"


class FailureCode(StrEnum):
    INVENTORY_EXHAUSTED = "INVENTORY_EXHAUSTED"
    TIER_NOT_FOUND = "TIER_NOT_FOUND"
    EVENT_CLOSED = "EVENT_CLOSED"
    EVENT_NOT_FOUND = "EVENT_NOT_FOUND"
    MAX_PER_USER_EXCEEDED = "MAX_PER_USER_EXCEEDED"
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class FailureReason(StrEnum):
    SOLD_OUT = "SOLD_OUT"
    TIER_NOT_FOUND = "TIER_NOT_FOUND"
    EVENT_NOT_FOUND = "EVENT_NOT_FOUND"
    EVENT_CLOSED = "EVENT_CLOSED"
    MAX_PER_USER_EXCEEDED = "MAX_PER_USER_EXCEEDED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


MAX_RETRY_COUNT_DEFAULT = 3
MAX_RETRY_COUNT_ROLLBACK = 5

VISIBILITY_TIMEOUT_PAYMENT = 30
VISIBILITY_TIMEOUT_INVENTORY = 45
VISIBILITY_TIMEOUT_ROLLBACK = 60
VISIBILITY_TIMEOUT_STATUS = 15

RESERVATION_TTL_MINUTES = 15
IDEMPOTENCY_TTL_HOURS = 24
STALE_LOCK_THRESHOLD_MINUTES = 5
